name: test-attack

on:
  pull_request_target:
    branches:
      - master

jobs:
   test1:
     environment: env1
     runs-on: windows-latest
     steps:
       - name: Checkout from PR branch  
         uses: actions/checkout@v4
         with: 
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
         # Using 20.x version as an example
       - name: Set Node.js 20.x for GitHub Action
         uses: actions/setup-node@v4
         with:
           node-version: 20.x

       - name: installing node_modules
         run: npm install 

       - name: Build GitHub Action
         run: npm run build

       - name: 'Run action'
         uses: ./
